# Generated by Django 3.2.9 on 2021-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('unit', models.CharField(choices=[('rub', 'Рубли'), ('usd', 'Доллары'), ('euro', 'Евро')], default='rub', max_length=6, verbose_name='Единица измерения валюты')),
                ('provider', models.CharField(max_length=300, verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
