# Generated by Django 3.2.9 on 2021-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211127_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(related_name='category', to='mainapp.Category', verbose_name='Категория товара'),
        ),
    ]
