# Generated by Django 3.2.9 on 2021-11-29 16:19

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211129_1807'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='goods',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
