version: '3.1'

services:
  db:
    image: postgres:13.4
    privileged: true
    restart: always
    ports:
      - 54323:5432

    environment:
      POSTGRES_USER: serzh
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test
  backend:
    build:
      context: ./store_project
    ports:
    - 8070:8070
    command:
      bash -c "
        python manage.py migrate &&
        export DJANGO_SETTINGS_MODULE=store_project.settings.prod_int &&
        gunicorn store_project.wsgi -b 0.0.0.0:8070
      "
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    ports:
      - 8077:8077
    depends_on:
      - backend